config/routes.rb
#encoding: utf-8
#include Rails.application.routes.url_helpers #在console中调用orders_path等
Shopqi::Application.routes.draw do

  mount Doorkeeper::Engine => '/oauth'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get '/shop'           , to: "shops#show"
      post '/themes/install', to: 'themes#install'
      get '/products'       , to: "products#index"
      get '/products/:id'   , to: "products#show"
      put '/variants/:id'   , to: "product_variants#update"
      get '/orders'         , to: "orders#index"
      get '/orders/:id'     , to: "orders#show"
      post '/webhooks'      , to: "webhooks#create"
    end
  end

  constraints(Domain::Wiki) do # 帮助文档
    devise_for :admin_users, ActiveAdmin::Devise.config
    scope module: :wiki do
      get '/'                         , to: 'wiki_pages#index'           , as: :wiki_pages_index
      get '/active_admin'             , to: redirect('/')
      resources :wiki_pages           , only:[:new                       , :create]
      get '/pages'                    , to: 'wiki_pages#pages'           , as: :wiki_pages_all
      match '/search'                 , to: 'wiki_pages#search'
      get '/history/:name'            , to: 'wiki_pages#history'
      get '/robots.txt'               , to: 'wiki_pages#robots'
      get '/:name'                    , to: 'wiki_pages#show'
      post '/destroy/:name'           , to: 'wiki_pages#destroy'
      get '/edit/:name'               , to: 'wiki_pages#edit'
      post '/compare/:name'           , to: 'wiki_pages#compare'
      get '/compare/:name/:sha1/:sha2', to: 'wiki_pages#compare_versions'
      post '/revert/:name/:sha1/:sha2', to: 'wiki_pages#revert'
      get '/:name/:sha'               , to: 'wiki_pages#show'
      post '/update'                  , to: 'wiki_pages#update'          , as: :update_page
      post '/preview'                 , to: 'wiki_pages#preview'
    end
  end

  constraints(Domain::Theme) do # 主题商店
    scope module: :theme do
      get '/', to: 'themes#index', as: :theme_index
      scope "/themes" do
        get '/login'                                , to: 'themes#login'       , as: :theme_login
        get '/logout'                               , to: 'themes#logout'      , as: :theme_logout
        get '/get_shop'                             , to: 'themes#get_shop'    , as: :theme_get_shop
        post '/login/authenticate'                  , to: 'themes#authenticate', as: :theme_authenticate
        get '/filter'                               , to: 'themes#filter'
        get '/:handle/styles/:style_handle'         , to: 'themes#show'        , as: :theme
        get '/:handle/styles/:style_handle/download', to: 'themes#download'    , as: :theme_download
        match '/:handle/styles/:style_handle/apply' , to: 'themes#apply'
      end
      get '/robots.txt'                             , to: 'themes#robots'

      begin 'client' # 作为oauth client
        get '/callback', to: redirect('/themes/get_shop')
      end
    end
  end

  ##### 商店及后台管理通用 #####
  match '/district/:id', to: 'district#list' # 地区选择(创建订单页面)
  scope module: :shop do
    match '/s/files/:id/theme/:theme_id/assets/:file.:format'            , to: 'shops#asset', file: /.+/
    match '/s/files/development/:id/theme/:theme_id/assets/:file.:format', to: 'shops#asset', file: /.+/ #开发中使用
    match '/s/files/test/:id/theme/:theme_id/assets/:file.:format'       , to: 'shops#asset', file: /.+/ #测试中使用
  end

  constraints(Domain::Shopqi) do
    scope module: :shopqi do # 官网
      root to: "home#page"
      get '/faq'       , to: 'home#faq'     , as: :faq
      get '/links'     , to: 'home#links'   , as: :home_links
      get '/about'     , to: 'home#about'   , as: :about
      scope "/tour" do # 功能演示
        get '/'        , to: 'home#tour'    , as: :tour_intro
        get '/store'   , to: 'home#store'   , as: :tour_store
        get '/design'  , to: 'home#design'  , as: :tour_design
        get '/security', to: 'home#security', as: :tour_security
        get '/features', to: 'home#features', as: :tour_features
      end
      get '/agreement', to: 'home#agreement'            , as: :agreement
      get '/signup'   , to: redirect('/services/signup')
      get '/login'    , to: 'home#login'
      scope "/services/signup" do
        # :confirmations, :omniauth_callbacks, :passwords, :registrations, :sessions, :unlocks
        devise_for :user, skip: [:sessions, :confirmations, :passwords], skip_helpers: true
        devise_scope :user do
          get '/new/professional'  , to: 'registrations#new'                         , as: :services_signup
          get "/new/:plan"         , to: "registrations#new"                         , as: :signup
          get "/check_availability", to: "registrations#check_availability"
          post "/user"             , to: "registrations#create"                      , as: :signup_user
          post "/verify_code"      , to: "registrations#verify_code" # 获取手机校验码
        end
      end
      get '/robots.txt', to: 'home#robots'
    end

    #官网后台管理
    ActiveAdmin.routes(self)
    authenticate :admin_user do # 管理员权限
      mount Resque::Server.new, at: "/resque" # 查看后台任务执行情况
    end

    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints(Domain::Store) do

    devise_for :user, skip: :registrations, controllers: {sessions: "admin/sessions"} # 登录

    scope module: :shop do # 前台商店
      scope '/account' do
        devise_for :customer, only: :passwords
        devise_scope :customer do
          get '/login'                     , to: 'sessions#new'        , as: :new_customer_session
          post '/login'                    , to: 'sessions#create'
          get '/logout'                    , to: 'sessions#destroy'
          get '/signup'                    , to: 'registrations#new'   , as: :new_customer_registration
          post '/customer'                 , to: 'registrations#create', as: :customer_registration
        end
        get '/orders/:token'               , to: 'account#show_order', as: :account_show_order
        get '/index'                       , to: 'account#index'     , as: :customer_root
        get '/'                            , to: 'account#index'
        resources :customer_addresses      , path: '/addresses'
      end
      match '/'                                             , to: 'shops#show'
      match '/password'                                     , to: 'shops#password'
      get   '/unavailable'                                  , to: 'shops#unavailable'
      get '/themes'                                         , to: 'shops#themes'        , as: :shop_themes_tip
      get '/search'                                         , to: 'search#show'
      get '/products/:handle'                               , to: 'products#show'       , as: :product_show
      get '/collections/:collection_handle/products/:handle', to: 'products#show'       , as: :collection_product_show
      get '/collections'                                    , to: 'collections#index'
      get '/products'                                       , to: 'collections#index'   , as: :shop_products
      get '/collections/all'                                , to: 'collections#show_all'
      get '/collections/:handle/products'                   , to: 'collections#show'
      get '/collections/:handle'                            , to: 'collections#show_with_types_or_vendors' , constraints: { handle: /types|vendors/ }
      get '/collections/:handle/:tags'                      , to: 'collections#show_with_tag'
      get '/collections/:handle'                            , to: 'collections#show'
      get '/pages/:handle'                                  , to: 'pages#show'
      post '/cart/add'                                      , to: 'cart#add'
      get '/cart'                                           , to: 'cart#show'
      post '/cart'                                          , to: 'cart#update'
      get '/cart/change/:variant_id'                        , to: 'cart#change'
      post '/cart/change'                                   , to: 'cart#change'
      post '/cart/clear'                                    , to: 'cart#clear'
      begin 'checkout' # 结算
        get '/carts/:cart_token'                            , to: 'order#new'
        get '/carts/:cart_token/shipping_rates/:code'       , to: 'order#shipping_rates'
        get '/carts/:cart_token/get_address'                , to: 'order#get_address'       , as: :get_address
        post '/carts/:cart_token/apply_discount'            , to: 'order#apply_discount'
        post '/carts/:cart_token'                           , to: 'order#create'
        post '/orders/notify'                               , to: 'order#notify'            , as: :notify_order
        get '/orders/done'                                  , to: 'order#done'              , as: :done_order
        match '/orders/tenpay_notify'                       , to: 'order#tenpay_notify'     , as: :tenpay_notify_order
        get '/orders/tenpay_done/:token'                    , to: 'order#tenpay_done'       , as: :tenpay_done_order
        get '/orders/:token'                                , to: 'order#show'              , as: :shop_order
      end
      get '/blogs/:handle'                                  , to: 'blogs#show'
      get '/blogs/:handle/:id'                              , to: 'articles#show'
      match '/blogs/:handle/:id/comments'                   , to: 'articles#add_comment'
      post '/contact'                                       , to: 'contact#create'
      get '/robots.txt'                                     , to: 'shops#robots'
    end

    scope module: :admin do # 用户后台管理(无 /admin 前缀)
      post '/kindeditor/upload_image', to: 'kindeditor#upload_image'
    end

    scope "/admin", module: :admin do # 用户后台管理

app/views/admin/pages/_page.html.haml
%tr(class="#{cycle(:odd, :even)}")
  %td
    =link_to page.title, page_path(page), title: "固定链接: #{page.handle}"
    -unless page.published?
      %span.status-hidden 隐藏
  %td.date=page.updated_at.to_s(:db)
  %td(style="text-align: center")=link_to image_tag('admin/icons/trash.gif'), page_path(page), remote: true, method: :delete, title: '删除它', class: :del, data: { confirm: '您确定要删除?' }

app/views/admin/pages/destroy.js.haml
window.location = '#{pages_path}';

app/views/admin/pages/index.html.haml
%h2#title 博客 &amp; 页面
#action-links
  %ul
    %li#create-page= link_to "新增页面", new_page_path
    %li#create-blog= link_to "新增博客", new_blog_path
    %li#create-article= link_to "新增文章", new_article_path
#pages
  %h4 页面
  %p.description
    页面是显示您的企业信息或者帮助信息的地方
    %br
    例如:
    %em "关于我们" , "服务条款"等等
  %table.standard-table(cellspacing="0" cellpadding="0" style="margin-bottom: 40px")
    %thead
      %tr
        %th(scope="col") 标题
        %th(scope="col" style="width: 150px;") 更新时间
        %th(scope="col" style="width: 50px") &nbsp;
    %tbody= render pages
  / PAGINATION LINKS
  #btm-nav.act-screen
    #pagination


= render partial:"admin/blogs/index"
= render partial:"admin/comments/index"

:javascript
  task_name = 'add_content';

app/views/admin/pages/new.html.haml
- use_kindeditor
%h2#title 新 增 页 面
#action-links
  %ul
    %li.no-icon=link_to '取消', pages_path
.group(style="margin-top:0")
  =form_for page do |f|
    #page-form.group-fields
      %dl
        %dt=f.label :title
        %dd
          =f.text_field :title, class: [:big, :sb]
          =f.hidden_field :handle
        %dt
          %label(for="page_body_html") 编写您的页面
        %dd(style="margin-bottom:0")=f.text_area :body_html, id: 'kindeditor'
    .group-actions
      %input#submit-page-btn.btn(name="commit" type="submit" value="保存")
      或者
      = link_to '取消', pages_path

:javascript
  task_name = 'add_content';

app/views/admin/pages/show.html.haml
-use_kindeditor

%h2#title= link_to page.title, "/pages/#{page.handle}", title: '在网店中查看此页面', target: '_blank'
#action-links
  %ul
    %li.no-icon
      %a#page-edit-link(href="#pages/edit") 修改
    %li.no-pad
      = link_to image_tag('admin/icons/trash.gif'), page_path(page), remote: true, method: :delete, title: '删除它', class: :del, data: { confirm: '您确定要删除?' }

.page-edit
  .group(style="margin-top:0")
    =form_for page do |f|
      #page-form.group-fields
        %dl
          %dt=f.label :title
          %dd=f.text_field :title, class: [:big, :sb]
          %dt#edit-handle-label(style="font-size:85%") 固定链接
          %dd#edit-handle.ssb
            %span.note==#{shop.primary_domain.url}/pages/
            =f.text_field :handle, style: 'width: 175px'
            %span.note
              (
              %a(href="#{wiki_url_with_port}/Handle" target="_blank")> 这是什么?
              )
          %dt
            %label(for="page_body_html") 编写您的页面
          %dd(style="margin-bottom:0")=f.text_area :body_html, id: 'kindeditor', style: "width: 895px; height: 282px;"
      .group-actions
        %input#submit-page-btn.btn(name="commit" type="submit" value="保存")
        或者
        = link_to '取消', '#'

#page-show.box2.article(style="cursor: pointer" title="点击修改")
  #page-body.textile.pgroup
    / Table Wrapper to prevent the layout from breaking due to invalid user text!
    %table.table-wrapper(style="width: 100%")
      %tr
        %td
          %p=raw page.body_html
.box2.sst
  / The parent is needed for the nested resource Article (blog is the parent)
  %h3 页面可见性
  %p.sb.note
    如果你不需要此页面显示在您的网店中，您可以设置它的可见性为
    = succeed "." do
      %em 隐藏
  =form_for page, remote: true, html: {id: 'edit_page_form'} do |f|
    =f.select :published, [['显示', true], ['隐藏', false]], {}, style: "width: 120px; font-size: 13px", onchange: "$('#edit_page_form').submit();"

:javascript
  App.init = function(){
    new App.Controllers.Pages();
    Backbone.history.start();
  }

  task_name = 'add_content';