config/routes.rb
        get '/login'                                , to: 'themes#login'       , as: :theme_login
        get '/logout'                               , to: 'themes#logout'      , as: :theme_logout
        get '/get_shop'                             , to: 'themes#get_shop'    , as: :theme_get_shop
        post '/login/authenticate'                  , to: 'themes#authenticate', as: :theme_authenticate
        get '/filter'                               , to: 'themes#filter'
        get '/:handle/styles/:style_handle'         , to: 'themes#show'        , as: :theme
        get '/:handle/styles/:style_handle/download', to: 'themes#download'    , as: :theme_download
        match '/:handle/styles/:style_handle/apply' , to: 'themes#apply'
      end
      get '/robots.txt'                             , to: 'themes#robots'

      begin 'client' # 作为oauth client
        get '/callback', to: redirect('/themes/get_shop')
      end
    end
  end

  ##### 商店及后台管理通用 #####
  match '/district/:id', to: 'district#list' # 地区选择(创建订单页面)
  scope module: :shop do
    match '/s/files/:id/theme/:theme_id/assets/:file.:format'            , to: 'shops#asset', file: /.+/
    match '/s/files/development/:id/theme/:theme_id/assets/:file.:format', to: 'shops#asset', file: /.+/ #开发中使用
    match '/s/files/test/:id/theme/:theme_id/assets/:file.:format'       , to: 'shops#asset', file: /.+/ #测试中使用
  end

  constraints(Domain::Shopqi) do
    scope module: :shopqi do # 官网
      root to: "home#page"
      get '/faq'       , to: 'home#faq'     , as: :faq
      get '/links'     , to: 'home#links'   , as: :home_links
      get '/about'     , to: 'home#about'   , as: :about
      scope "/tour" do # 功能演示
        get '/'        , to: 'home#tour'    , as: :tour_intro
        get '/store'   , to: 'home#store'   , as: :tour_store
        get '/design'  , to: 'home#design'  , as: :tour_design
        get '/security', to: 'home#security', as: :tour_security
        get '/features', to: 'home#features', as: :tour_features
      end
      get '/agreement', to: 'home#agreement'            , as: :agreement
      get '/signup'   , to: redirect('/services/signup')
      get '/login'    , to: 'home#login'
      scope "/services/signup" do
        # :confirmations, :omniauth_callbacks, :passwords, :registrations, :sessions, :unlocks
        devise_for :user, skip: [:sessions, :confirmations, :passwords], skip_helpers: true
        devise_scope :user do
          get '/new/professional'  , to: 'registrations#new'                         , as: :services_signup
          get "/new/:plan"         , to: "registrations#new"                         , as: :signup
          get "/check_availability", to: "registrations#check_availability"
          post "/user"             , to: "registrations#create"                      , as: :signup_user
          post "/verify_code"      , to: "registrations#verify_code" # 获取手机校验码
        end
      end
      get '/robots.txt', to: 'home#robots'
    end

    #官网后台管理
    ActiveAdmin.routes(self)
    authenticate :admin_user do # 管理员权限
      mount Resque::Server.new, at: "/resque" # 查看后台任务执行情况
    end

    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints(Domain::Store) do

    devise_for :user, skip: :registrations, controllers: {sessions: "admin/sessions"} # 登录

    scope module: :shop do # 前台商店
      scope '/account' do
        devise_for :customer, only: :passwords
        devise_scope :customer do
          get '/login'                     , to: 'sessions#new'        , as: :new_customer_session
          post '/login'                    , to: 'sessions#create'
          get '/logout'                    , to: 'sessions#destroy'
          get '/signup'                    , to: 'registrations#new'   , as: :new_customer_registration
          post '/customer'                 , to: 'registrations#create', as: :customer_registration
        end
        get '/orders/:token'               , to: 'account#show_order', as: :account_show_order
        get '/index'                       , to: 'account#index'     , as: :customer_root
        get '/'                            , to: 'account#index'
        resources :customer_addresses      , path: '/addresses'
      end
      match '/'                                             , to: 'shops#show'
      match '/password'                                     , to: 'shops#password'
      get   '/unavailable'                                  , to: 'shops#unavailable'
      get '/themes'                                         , to: 'shops#themes'        , as: :shop_themes_tip
      get '/search'                                         , to: 'search#show'
      get '/products/:handle'                               , to: 'products#show'       , as: :product_show
      get '/collections/:collection_handle/products/:handle', to: 'products#show'       , as: :collection_product_show
      get '/collections'                                    , to: 'collections#index'
      get '/products'                                       , to: 'collections#index'   , as: :shop_products
      get '/collections/all'                                , to: 'collections#show_all'
      get '/collections/:handle/products'                   , to: 'collections#show'
      get '/collections/:handle'                            , to: 'collections#show_with_types_or_vendors' , constraints: { handle: /types|vendors/ }
      get '/collections/:handle/:tags'                      , to: 'collections#show_with_tag'
      get '/collections/:handle'                            , to: 'collections#show'
      get '/pages/:handle'                                  , to: 'pages#show'
      post '/cart/add'                                      , to: 'cart#add'
      get '/cart'                                           , to: 'cart#show'
      post '/cart'                                          , to: 'cart#update'
      get '/cart/change/:variant_id'                        , to: 'cart#change'
      post '/cart/change'                                   , to: 'cart#change'
      post '/cart/clear'                                    , to: 'cart#clear'
      begin 'checkout' # 结算
        get '/carts/:cart_token'                            , to: 'order#new'
        get '/carts/:cart_token/shipping_rates/:code'       , to: 'order#shipping_rates'
        get '/carts/:cart_token/get_address'                , to: 'order#get_address'       , as: :get_address
        post '/carts/:cart_token/apply_discount'            , to: 'order#apply_discount'
        post '/carts/:cart_token'                           , to: 'order#create'
        post '/orders/notify'                               , to: 'order#notify'            , as: :notify_order
        get '/orders/done'                                  , to: 'order#done'              , as: :done_order
        match '/orders/tenpay_notify'                       , to: 'order#tenpay_notify'     , as: :tenpay_notify_order
        get '/orders/tenpay_done/:token'                    , to: 'order#tenpay_done'       , as: :tenpay_done_order
        get '/orders/:token'                                , to: 'order#show'              , as: :shop_order
      end
      get '/blogs/:handle'                                  , to: 'blogs#show'
      get '/blogs/:handle/:id'                              , to: 'articles#show'
      match '/blogs/:handle/:id/comments'                   , to: 'articles#add_comment'
      post '/contact'                                       , to: 'contact#create'
      get '/robots.txt'                                     , to: 'shops#robots'
    end

    scope module: :admin do # 用户后台管理(无 /admin 前缀)
      post '/kindeditor/upload_image', to: 'kindeditor#upload_image'
    end

    scope "/admin", module: :admin do # 用户后台管理
      match "/"                             , to: "home#dashboard"                      , as: :user_root # user_root_path为用户成功登录后的跳转地址
      get '/message'                        , to: "home#message"                        , as: :home_message

      resources :api_clients

      match "/general_preferences"          , to: "shops#edit"
      match "/notifications"                , to: "emails#index"
      match "/notifications/subscribe"      , to: "emails#follow"
      match "/notifications/:id/unsubscribe", to: "emails#unfollow"                     , as: 'unfollow'
      match "/notifications/preview_:view_type"   , to: 'emails#preview'
      match '/support'                      , to: redirect('http://support.shopqi.com/'), as: 'support'
      get '/lookup/query'                   , to: 'home#query'
      post "/dashboard/complete_task/:name" , to: "home#complete_task"                  , as: :complete_task
      post "/dashboard/launch"              , to: "home#launch"                         , as: :launch
      post "/dashboard/skip_tutorial"       , to: "home#skip_tutorial"                  , as: :skip_tutorial

      resources :webhooks, only: [:create, :destroy]

      resources :shops, only: [:update]

      resources :payments

      scope "notifications" do
        resources :emails, only:[:index,:edit,:update]
      end

      resources :countries, only: [:create,:new,:edit,:index,:destroy,:update]

      resources :shippings, only: [:index, :create, :destroy] do
        resources :weight_based_shipping_rates, only: [:edit,:update,:create,:destroy]
        resources :price_based_shipping_rates, only: [:edit,:update,:create,:destroy]
      end

      resources :orders, only: [:index, :update, :show, :destroy] do
        collection do
          post :set
        end
        member do
          post :close  #关闭
          post :open   #重新打开
          put  :cancel #取消
          post :previous #上一订单
          post :next     #下一订单
          post :alipay_refund_notify, as: :alipay_refund_notify  #支付宝退款通知
        end

        # 配送记录(物流信息)
        resources :fulfillments, except: [:index, :new, :create, :edit, :destroy] do
          collection do

app/controllers/admin/customers_controller.rb
#encoding: utf-8
class Admin::CustomersController < Admin::AppController
  prepend_before_filter :authenticate_user!
  layout 'admin'

  expose(:shop) { current_user.shop }
  expose(:customers) { shop.customers }
  expose(:customer_groups) { shop.customer_groups }
  expose(:customer)
  expose(:tags) { shop.customer_tags.previou_used }
  expose(:customer_groups_json) do
    customer_groups.to_json({
      except: [ :created_at, :updated_at ]
    })
  end
  expose(:customer_json) do
    customer.to_json({
      include: {
        addresses: { methods: [:province_name, :city_name, :district_name] },
        orders: {
          only: [:id, :name, :status, :created_at, :total_price],
          methods: [ :status_name, :financial_status_name, :fulfillment_status_name]
        }
      },
      methods: [ :default_address, :order, :total_spent, :status_name, :tags_text ],
      except: [ :created_at, :updated_at ]
    })
  end
  expose(:tags_json) { tags.to_json }
  expose(:page_sizes) { KeyValues::PageSize.hash }
  expose(:primary_filters) { KeyValues::Customer::PrimaryFilter.all }
  expose(:secondary_filters_integer) { KeyValues::Customer::SecondaryFilter::Integer.hash }
  expose(:secondary_filters_date) { KeyValues::Customer::SecondaryFilter::Date.hash }
  expose(:boolean) { KeyValues::Customer::Boolean.hash }
  expose(:status) { KeyValues::Customer::State.hash }

  def index
    render action: :blank_slate if shop.customers.empty?
  end

  def new
    customer.addresses.build if customer.addresses.empty?
  end

  def create
    customer.password = Random.new.rand(100000..999999) #用于在后台新增用户时，为顾客增加一个随机密码
    if customer.save
      redirect_to customer_path(customer)
    else
      render action: :new
    end
  end

  def update
    customer.save
    render nothing: true
  end

  def show
  end

  def search
    customers = if params[:q] or params[:f]
      conditions = {}
      unless params[:f].blank? # 过滤器
        params[:f].each do |filter|
          condition, value = filter.split ':'
          value = case value.to_sym
            # 日期
            when :last_week then 1.week.ago
            when :last_month then 1.month.ago
            when :last_3_months then 3.month.ago
            when :last_year then 3.month.ago
            # 是否
            when :true then true
            when :false then false
            else
              value
          end
          case condition.to_sym
            when :last_order_date
              conditions[:orders_created_at_gt] = value
            when :last_abandoned_order_date
              conditions[:orders_status_eq] = :abandoned
              conditions[:orders_created_at_gt] = value
            when :accepts_marketing, :status
              conditions["#{condition}_eq"] = value
            else
              conditions[condition] = value
          end
        end
      end
      conditions.merge! name_contains: params[:q] unless params[:q].blank?
      shop.customers.metasearch(conditions)
    else
      shop.customers
    end
    limit = params[:limit] || 25
    page = params[:page] || 1
    customers = customers.page(page).per(limit)
    render json: {total_count: customers.total_count, results: customers.as_json(
      methods: [ :default_address, :order, :total_spent ],
      except: [ :created_at, :updated_at ]
    )}
  end
end

app/views/admin/customers/_export.html.haml
#export-customers.box2.ssb.sst.hide
  %h3 导出您的顾客信息
  %p.sb
    您的顾客信息将导出为
    %strong \.csv 文件
    (以逗号分隔).
  %a#export_current_search_csv.btn.sr(href="#") 导出当前分组
  %a#export_csv.btn(href="/admin/customers/export.csv") 导出所有顾客

app/views/admin/customers/_menu.html.haml
%h2#title 顾客管理
#action-links
  %ul
    %li#customer=link_to "新增顾客信息", new_customer_path
    -#
      %li.csv
        %a#show_export_customers(href="#") 导出顾客信息
      %li.csv
        %a(href="/admin/customer_imports") 导入顾客信息
=render "shared/noscript"
=render "shared/upgrade_ie"
-#=render :export

app/views/admin/customers/blank_slate.html.haml
=render "menu"

#blank-slate.blank-slate.clearfix.ppb
  .heading
    %h3 您暂时还没有顾客.
    %p 在这里，您以后能看到顾客记录，并对这些记录进行管理.
  .details.clearfix
    #blank-slate-features.features.default.fl
      %ul
        %li.overview-your-customers
          %h3 管理您的顾客
          %p 跟踪您的顾客订单历史，找出谁的订单总额最多，或者谁是您的商店常客.
        %li.filter-your-customers
          %h3 过滤您的顾客
          %p 通过消费总额、所在地区等条件来过滤顾客. 您可以将这些条件保存为顾客分组.
        %li.last.group-your-customers
          %h3 创建顾客分组
          %p 顾客分组用于保存过滤条件，方便您关注顾客.
    /.features
    #blank-slate-screenshot.screenshot.fl
      =image_tag 'admin/customer-blank-slate.jpg'
      .overlay.group-your-customers(style="width:139px; height:126px; top:60px; left:8px;")
      .overlay.filter-your-customers(style="width:375px; height:68px; top:60px; left:168px;")
      .overlay.overview-your-customers(style="width:375px; height:390px; top:158px; left:168px;")
    /.screenshot
  /.details
/#blank-slate

:javascript
  $('#blank-slate').blank_slate();

app/views/admin/customers/index.html.haml
=render "menu"

.clearfix.ppb(style="padding-bottom:40px;")
  .col-4(style="width:242px; position:relative;")
    #customer-group-container.box2.preview-box
      .preview 顾客分组
      %ul#customer-groups
  .col-8.last(style="width:648px;")
    #order-filters
      %form#customer-search(action="/admin/customers" method="get" onsubmit="return false")
        #customer-filters.box2.clearfix
          .clearfix
            %input#customer-search_field.filter-text(autocomplete="off" data-hint="输入查询内容过滤信息..." name="q" onsubmit="return false" type="text")
            .filter-info
              #search-filter_summary.summary(style="display:none;")
                %span.filter-message 1 active filter
                %span.remove
                  %a(href="#") x
            #customer-search_msg(style='padding-left: 10px; background-image: none; background-color: transparent;') 找到 0位 顾客
          #customer-search_filters
      #customer-search_add_filters.toggle-drop.box2(style="display:none;")
        %h3
          %span.hint 增加过滤器 通过订单总额等条件过滤顾客信息
        .clearfix
          %form#search-filter(onsubmit="return false")
            %select#search-filter_primary(name="primary-value")
              -primary_filters.each do |filter|
                %option{value:filter.code, clazz:filter.clazz}=filter.name
            %select#search-filter_secondary(name="secondary-value")
            #search-filter_value_div
              %input#search-filter_value.condition.filter_text_value(name="filter-value" style="width:120px" type="text")
            .apply_filter
              %input#search-filter_apply.btn.apply-filter(name="commit" onclick="return false;" type="submit" value="新增过滤器")
    .sst(style="height: 32px;")
      %table#customer-table_status(cellpadding="0" cellspacing="0" style="display:none")
        %tr
          %td(style="text-align:left;vertical-align: middle")
            %select#customer-table_actions(name="operation")
              %option(selected="selected" style="color:#888" value="") 选择操作...
              %option.indent(value="add_tag") 标记顾客
              %option.indent(value="remove_tag") 删除标记
          %td(style="text-align:right;vertical-align: middle")
            %span#customer-count.note(style="margin-bottom: 5px") &nbsp;
    #customers.ssb
      #customer-search_overlay.hide
        %p 顾客信息正在更新&hellip;
      %table#customer-table.standard-table.row-space.select-table(cellspacing="0" cellpadding="0")
        %thead
          %tr#customer-search_customer
            %th.nosort(style="width: 16px")
              %input#select-all(type="checkbox" autocomplete="off")
            %th.sortcol(data-value="last_name_sortable") 姓名
            %th &nbsp;
            %th.sortcol(data-value="location") 地址
            %th.sortcol(data-value="total_spent" style="text-align: right; padding-right: 4px ! important; background-position: 5% center ! important;") 消费金额
            %th.sortcol(data-value="customers_count") 订单数
            %th.sortcol(data-value="last_customer_date") 最近订单
        %tbody#customer-table_list.ssb
      #customer-search_empty.c(style="display:none;") 没有顾客信息符合查询条件.
    #customer-search_pagination
      #pagination
.box2.clearfix
  .fl
    %p
      顾客帐号被
      %strong 启用
      并且
      %strong 可选
      \.
      %a(href="/admin/payments#customer-accounts") 修改这些配置
  .fr
    每页显示条数:
    %select#customer-search_limit(style="width:60px")=options_for_select page_sizes, 50
#display_message.display_message(style="display:none;")
#hidden-content(style="display:none;")
  %a#hidden-closure-link.closure-lightbox(href="/admin/customers/tag_form" title="Tag Customers") 新增标记
  #add-note
    #customer-note.message
      #customer-note_body
      %form#customer-note_form
        %textarea(name="customer[note]")
        %input#customer-note_customer_id(type="text" name="customer-note_customer_id")
        %p
          %input#customer-note_submit.btn(name="commit" type="submit" value="Save note")
          或者
          %a(href="#" onclick="customernote.toggleForm(); return false;") 取消

%script(id="show-customer-item" type="text/x-handlebars-template")
  %td(style="padding-top: 5px")
    %input.selector(style="margin: 3px 0" type="checkbox")
  %td.customer-name
    %a.customer-link(href="/admin/customers/{{{id}}}") {{{name}}}
    .display_message.clearfix(id="customer-display-{{{id}}}" style="display:none;")
      .customer-details
        %span.name
          %a(href="/admin/customers/{{{id}}}") {{{name}}}
        %span.marketing 接受营销邮件
        %span.phone-number {{{phone}}}
        %span.info
          %a.skype(href="skype://{{{phone}}}") 通过Skype拨打电话
          %a.email(href="mailto:{{{email}}}") {{{email}}}
  %td
    %a.customer-display-link(href="#" onclick="return false;")
      %span.contact-details.customer-display-link(data-popup-id="customer-display-{{{id}}}") i
  %td
    {{#if default_address}}
    {{#with default_address}}
    {{{province_name}}}{{{city_name}}}{{{district_name}}}
    {{/with}}
    {{/if}}
  %td.r {{{total_spent}}}
  %td.c {{{orders_count}}}
  %td
    {{#if order}}
    %span.note
      %a(href="/admin/orders/{{{order.id}}}") {{{order.name}}}
      {{{date order.created_at "MM-dd"}}}
    {{/if}}

%script(id="customer-group-item" type="text/x-handlebars-template")
  {{#if is_group}}
  %a.delete(href="/admin/customer_groups/{{{id}}}" data-confirm="您确定要删除吗?")=image_tag('admin/icons/trash.gif')
  {{/if}}
  %h3 {{{name}}}
  %ul.filters
    {{#if term}}
    %li 关键字:{{{term}}}
    {{/if}}
    {{#each filters}}
    %li
      %span(class="label-text") {{{condition_name}}} {{{value_name}}}
    {{/each}}
  {{#if is_current_search}}
  %a#save_customer_group_link.btn.closure-lightbox(href='#') 保存为顾客分组
  {{/if}}
  {{#if is_group}}
  %a.update.btn(href="/admin/customer_groups/{{{id}}}" style="display:none") 更新
  {{/if}}
%script(id="customer-search_filters-item" type="text/x-handlebars-template")
  %span.label-text {{{condition_name}}} {{{value_name}}}
  %a.close-filter-tag(href="#") x
%script(id="new-customer-group-item" type="text/x-handlebars-template")
  =dialog '保存顾客分组' do
    %form#create_customer_group.clearfix(onsubmit='return false')
      %p(style="font-size:12px; margin-bottom:10px; color:#777;") 请输入新的分组名称
      %input#new_group_name.name(name="customer_group[name]")
      %input#save_group_button.btn(type="submit" value="保存")

:javascript
  App.init = function(){
    new App.Controllers.Customers.Index();
    Backbone.history.start();
  }

  secondary_filters = {
    integer: #{secondary_filters_integer.to_json},
    date: #{secondary_filters_date.to_json},
    boolean: #{boolean.to_json},
    status: #{status.to_json}
  }

  App.customers = new App.Collections.Customers();
  App.customer_groups = new App.Collections.CustomerGroups();
  App.customer_group = new App.Models.CustomerGroup(); //用于分组与查询的中介
  App.customer_groups.refresh(#{customer_groups_json});
  new App.Views.Customer.Index.Index({collection: App.customers})
  new App.Views.CustomerGroup.Index.Index({collection: App.customer_groups})

app/views/admin/customers/new.html.haml
%h2#title 新增顾客
#action-links
  %ul
    %li.no-icon=link_to "返回", customers_path
=render "shared/noscript"
=render "shared/upgrade_ie"
=message_block on: customer
.col-4
  #customer-box.box2.preview
    %table#customer-summary(cellpadding="0" cellspacing="0")
      %tr.first
        %td.attribute=image_tag 'admin/icons/customer.gif', id: :gravatar
        %td.value
          %h3
            %span#preview_customer_first_name
            %span#preview_customer_last_name
          %p(style="line-height:16px;")
            %a(href="#")
              %span#preview_customer_email
            %br/
            %span#preview_customer_phone
      %tr#address_preview
        %td.attribute 默认地址
        %td.value
          %span#preview_customer_company
          %span#preview_customer_province
          %br/
          %span#preview_customer_city
          %br/
          %span#preview_customer_district
          %br/
          %span#preview_customer_address1
          %span#preview_customer_address2
          %span#preview_customer_zip
#new-customer-screen.customer.col-8.last
  =form_for customer, validate: false do |f|
    .section-header(style="margin-top:0;") 顾客信息
    .customer-group.white.clearfix
      .pb.clearfix
        .fl
          =f.label :name
          =f.text_field :name
      .pb.clearfix
        .fl
          =f.label :email
          =f.text_field :email
    #customer-addresses
    %div
      .section-header
        地址信息
        %span.instruction 非必填
      .customer-group.white
        =f.fields_for :addresses, child_index: '' do |a|
          .pb.clearfix
            .fl
              =a.label :company
              =a.text_field :company, class: [:sr, :name, :company]
            .fl
              =a.label :phone
              =a.text_field :phone, class: :phone
          .pb.clearfix.region
            .fl(style="margin-right:10px")
              %label(for="customer_addresses_0_province") 地区
              =a.select :province, District.list, {include_blank: '--省份--'}, style: 'width: 106px'
              =a.select :city, District.list(customer.addresses.first.province), {include_blank: '--城市--'}, style: 'width: 106px'
              =a.select :district, District.list(customer.addresses.first.city), {include_blank: '--地区--'}, style: 'width: 106px'
          .pb.clearfix
            .fl
              =a.label :address1
              =a.text_field :address1, class: :city
            .fl
              =a.label :zip
              =a.text_field :zip, class: :postal
      .customer-group.white
        .pb.clearfix
          .fl=f.check_box :accepts_marketing
          .fl=f.label :accepts_marketing
    .section-header
      备注
      %span.instruction 非必填
    .customer-group.white=f.text_area :note, size: '40x20'
    .section-header
      标签
      %span.instruction 非必填
    .customer-group.white.ssb
      %p.note.sb 多个关键词之间用逗号(,)隔开。
      =f.text_field :tags_text, id: :tags_text
      -if tags.empty?
        %p.note 例如: VIP
      -else
        %p.note(style="clear: both") 最近使用过的标签，单击增加。
        %ul#tag-list.tag-list.clearfix
          -tags.each do |tag|
            %li
              %a(href="#")=tag.name
    .group-actions
      %input.btn(name="commit" type="submit" value="保存")
      或者
      =link_to "取消", customers_path

:javascript
  new App.Views.Customer.New.Index();