config/routes.rb
#encoding: utf-8
#include Rails.application.routes.url_helpers #在console中调用orders_path等
Shopqi::Application.routes.draw do

  mount Doorkeeper::Engine => '/oauth'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get '/shop'           , to: "shops#show"
      post '/themes/install', to: 'themes#install'
      get '/products'       , to: "products#index"
      get '/products/:id'   , to: "products#show"
      put '/variants/:id'   , to: "product_variants#update"
      get '/orders'         , to: "orders#index"
      get '/orders/:id'     , to: "orders#show"
      post '/webhooks'      , to: "webhooks#create"
    end
  end

  constraints(Domain::Wiki) do # 帮助文档
    devise_for :admin_users, ActiveAdmin::Devise.config
    scope module: :wiki do
      get '/'                         , to: 'wiki_pages#index'           , as: :wiki_pages_index
      get '/active_admin'             , to: redirect('/')
      resources :wiki_pages           , only:[:new                       , :create]
      get '/pages'                    , to: 'wiki_pages#pages'           , as: :wiki_pages_all
      match '/search'                 , to: 'wiki_pages#search'
      get '/history/:name'            , to: 'wiki_pages#history'
      get '/robots.txt'               , to: 'wiki_pages#robots'
      get '/:name'                    , to: 'wiki_pages#show'
      post '/destroy/:name'           , to: 'wiki_pages#destroy'
      get '/edit/:name'               , to: 'wiki_pages#edit'
      post '/compare/:name'           , to: 'wiki_pages#compare'
      get '/compare/:name/:sha1/:sha2', to: 'wiki_pages#compare_versions'
      post '/revert/:name/:sha1/:sha2', to: 'wiki_pages#revert'
      get '/:name/:sha'               , to: 'wiki_pages#show'
      post '/update'                  , to: 'wiki_pages#update'          , as: :update_page
      post '/preview'                 , to: 'wiki_pages#preview'
    end
  end

  constraints(Domain::Theme) do # 主题商店
    scope module: :theme do
      get '/', to: 'themes#index', as: :theme_index
      scope "/themes" do
        get '/login'                                , to: 'themes#login'       , as: :theme_login
        get '/logout'                               , to: 'themes#logout'      , as: :theme_logout
        get '/get_shop'                             , to: 'themes#get_shop'    , as: :theme_get_shop
        post '/login/authenticate'                  , to: 'themes#authenticate', as: :theme_authenticate
        get '/filter'                               , to: 'themes#filter'
        get '/:handle/styles/:style_handle'         , to: 'themes#show'        , as: :theme
        get '/:handle/styles/:style_handle/download', to: 'themes#download'    , as: :theme_download
        match '/:handle/styles/:style_handle/apply' , to: 'themes#apply'
      end
      get '/robots.txt'                             , to: 'themes#robots'

      begin 'client' # 作为oauth client
        get '/callback', to: redirect('/themes/get_shop')
      end
    end
  end

  ##### 商店及后台管理通用 #####
  match '/district/:id', to: 'district#list' # 地区选择(创建订单页面)
  scope module: :shop do
    match '/s/files/:id/theme/:theme_id/assets/:file.:format'            , to: 'shops#asset', file: /.+/
    match '/s/files/development/:id/theme/:theme_id/assets/:file.:format', to: 'shops#asset', file: /.+/ #开发中使用
    match '/s/files/test/:id/theme/:theme_id/assets/:file.:format'       , to: 'shops#asset', file: /.+/ #测试中使用
  end

  constraints(Domain::Shopqi) do
    scope module: :shopqi do # 官网
      root to: "home#page"
      get '/faq'       , to: 'home#faq'     , as: :faq
      get '/links'     , to: 'home#links'   , as: :home_links
      get '/about'     , to: 'home#about'   , as: :about
      scope "/tour" do # 功能演示
        get '/'        , to: 'home#tour'    , as: :tour_intro
        get '/store'   , to: 'home#store'   , as: :tour_store
        get '/design'  , to: 'home#design'  , as: :tour_design
        get '/security', to: 'home#security', as: :tour_security
        get '/features', to: 'home#features', as: :tour_features
      end
      get '/agreement', to: 'home#agreement'            , as: :agreement
      get '/signup'   , to: redirect('/services/signup')
      get '/login'    , to: 'home#login'
      scope "/services/signup" do
        # :confirmations, :omniauth_callbacks, :passwords, :registrations, :sessions, :unlocks
        devise_for :user, skip: [:sessions, :confirmations, :passwords], skip_helpers: true
        devise_scope :user do
          get '/new/professional'  , to: 'registrations#new'                         , as: :services_signup
          get "/new/:plan"         , to: "registrations#new"                         , as: :signup
          get "/check_availability", to: "registrations#check_availability"
          post "/user"             , to: "registrations#create"                      , as: :signup_user
          post "/verify_code"      , to: "registrations#verify_code" # 获取手机校验码
        end
      end
      get '/robots.txt', to: 'home#robots'
    end

    #官网后台管理
    ActiveAdmin.routes(self)
    authenticate :admin_user do # 管理员权限
      mount Resque::Server.new, at: "/resque" # 查看后台任务执行情况
    end

    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints(Domain::Store) do

    devise_for :user, skip: :registrations, controllers: {sessions: "admin/sessions"} # 登录

    scope module: :shop do # 前台商店
      scope '/account' do
        devise_for :customer, only: :passwords
        devise_scope :customer do
          get '/login'                     , to: 'sessions#new'        , as: :new_customer_session
          post '/login'                    , to: 'sessions#create'
          get '/logout'                    , to: 'sessions#destroy'
          get '/signup'                    , to: 'registrations#new'   , as: :new_customer_registration
          post '/customer'                 , to: 'registrations#create', as: :customer_registration
        end
        get '/orders/:token'               , to: 'account#show_order', as: :account_show_order
        get '/index'                       , to: 'account#index'     , as: :customer_root
        get '/'                            , to: 'account#index'
        resources :customer_addresses      , path: '/addresses'
      end
      match '/'                                             , to: 'shops#show'
      match '/password'                                     , to: 'shops#password'
      get   '/unavailable'                                  , to: 'shops#unavailable'
      get '/themes'                                         , to: 'shops#themes'        , as: :shop_themes_tip
      get '/search'                                         , to: 'search#show'
      get '/products/:handle'                               , to: 'products#show'       , as: :product_show
      get '/collections/:collection_handle/products/:handle', to: 'products#show'       , as: :collection_product_show
      get '/collections'                                    , to: 'collections#index'
      get '/products'                                       , to: 'collections#index'   , as: :shop_products
      get '/collections/all'                                , to: 'collections#show_all'
      get '/collections/:handle/products'                   , to: 'collections#show'
      get '/collections/:handle'                            , to: 'collections#show_with_types_or_vendors' , constraints: { handle: /types|vendors/ }
      get '/collections/:handle/:tags'                      , to: 'collections#show_with_tag'
      get '/collections/:handle'                            , to: 'collections#show'
      get '/pages/:handle'                                  , to: 'pages#show'
      post '/cart/add'                                      , to: 'cart#add'
      get '/cart'                                           , to: 'cart#show'
      post '/cart'                                          , to: 'cart#update'
      get '/cart/change/:variant_id'                        , to: 'cart#change'
      post '/cart/change'                                   , to: 'cart#change'
      post '/cart/clear'                                    , to: 'cart#clear'
      begin 'checkout' # 结算
        get '/carts/:cart_token'                            , to: 'order#new'
        get '/carts/:cart_token/shipping_rates/:code'       , to: 'order#shipping_rates'
        get '/carts/:cart_token/get_address'                , to: 'order#get_address'       , as: :get_address
        post '/carts/:cart_token/apply_discount'            , to: 'order#apply_discount'
        post '/carts/:cart_token'                           , to: 'order#create'
        post '/orders/notify'                               , to: 'order#notify'            , as: :notify_order
        get '/orders/done'                                  , to: 'order#done'              , as: :done_order
        match '/orders/tenpay_notify'                       , to: 'order#tenpay_notify'     , as: :tenpay_notify_order
        get '/orders/tenpay_done/:token'                    , to: 'order#tenpay_done'       , as: :tenpay_done_order
        get '/orders/:token'                                , to: 'order#show'              , as: :shop_order
      end
      get '/blogs/:handle'                                  , to: 'blogs#show'
      get '/blogs/:handle/:id'                              , to: 'articles#show'
      match '/blogs/:handle/:id/comments'                   , to: 'articles#add_comment'
      post '/contact'                                       , to: 'contact#create'
      get '/robots.txt'                                     , to: 'shops#robots'
    end

    scope module: :admin do # 用户后台管理(无 /admin 前缀)
      post '/kindeditor/upload_image', to: 'kindeditor#upload_image'
    end

    scope "/admin", module: :admin do # 用户后台管理

app/controllers/admin/orders_controller.rb
#encoding: utf-8
class Admin::OrdersController < Admin::AppController
  prepend_before_filter :authenticate_user!, except: :alipay_refund_notify
  skip_before_filter :check_permission     , only: :alipay_refund_notify
  skip_before_filter :force_domain         , only: :alipay_refund_notify
  layout 'admin'

  expose(:shop) { current_user.shop }
  expose(:orders) { shop.orders }
  expose(:order)
  expose(:customer) { order.customer }
  expose(:order_json) do
    order.to_json({
      methods: [ :gateway, :status_name, :financial_status_name, :fulfillment_status_name, :shipping_rate_price, :other_orders ],
      include: {
        line_items: { methods: [:total_price, :fulfillment_created_at, :product_deleted] },
        transactions: {},
        histories: {},
        discount: { only: [:code, :amount] }
      },
      except: [ :updated_at ]
    })
  end
  expose(:status) { KeyValues::Order::Status.hash }
  expose(:financial_status) { KeyValues::Order::FinancialStatus.hash }
  expose(:fulfillment_status) { KeyValues::Order::FulfillmentStatus.hash }
  expose(:cancel_reasons) { KeyValues::Order::CancelReason.hash }
  expose(:tracking_companies) { KeyValues::Order::TrackingCompany.hash }
  expose(:latest_tracking_company) { shop.redis order.latest_tracking_company_key }
  expose(:latest_tracking_number) { shop.redis order.latest_tracking_number_key }
  expose(:page_sizes) { KeyValues::PageSize.hash }

  def index
    render action: :blank_slate and return if shop.orders.empty?
    @limit = 50
    page = params[:page] || 1
    orders = if params[:search]
      @limit = params[:search].delete(:limit) || @limit
      params[:search][:financial_status_ne] = :abandoned if params[:search][:financial_status_eq].blank?
      params[:search][:status_eq] = :open if params[:search][:status_eq].blank?
      shop.orders.metasearch(params[:search])
    else
      shop.orders.metasearch(status_eq: :open, financial_status_ne: :abandoned)
    end
    orders = orders.page(page).per(@limit)
    @pagination = {total_count: orders.total_count, page: page.to_i, limit: @limit, results: orders.as_json(
      include: {
        customer: {only: [:id, :name]},
        line_items: {only: [:name, :quantity]},
        shipping_address: {only: [:name], methods: [:info]}
      },
      methods: [ :status_name, :financial_status_name, :fulfillment_status_name, :shipping_name ],
      except: [ :updated_at ]
    )}.to_json
    respond_to do |format|
      format.html
      format.js { render json: @pagination }
    end
  end

  def show
    if order.cancelled? and transaction = order.transactions.pending_refund.first
      payment = order.payment
      data = [{
        'trade_no' => order.trade_no,
        'amount' => transaction.amount,
        'reason' => '协商退款'
      }]
      @refund_apply_url = Gateway::Alipay::Refund.apply_url(payment.account, payment.key, payment.email, 'batch_no' => transaction.batch_no, 'data' => data, 'notify_url' => "#{request.protocol}#{shop.domains.myshopqi.host}#{alipay_refund_notify_order_path(order)}")
    end
  end

  # 批量修改
  def set
    operation = params[:operation].to_sym
    ids = params[:orders]
    if [:open, :close].include?(operation)
      value = (operation == :close) ? :closed : :open
      Order.transaction do
        shop.orders.find(ids).each do |order|
          order.status = value
          order.save
        end
      end
    else #支付授权
    end
    render nothing: true
  end

  def update
    render text: order.save
  end

  def close
    order.status = :closed
    order.save
    redirect_to orders_path
  end

  def open
    order.status = :open
    order.save
    redirect_to order_path(order)
  end

  def cancel
    amount = params[:refund] ? order.total_price : 0
    order.cancel!(email: params[:email], amount: amount)
    path = params[:refund] ? order_path(order) : orders_path # 需要退款直接返回订单详情
    redirect_to path
  end

  def destroy
    order.destroy
    redirect_to orders_path
  end

  begin 'from pay gateway'

    begin 'alipay'

      def alipay_refund_notify # 退款通知
        text = 'fail'
        shop = ShopDomain.at(request.host).shop
        if alipay = shop.payments.alipay
          notification = Gateway::Alipay::Refund::Notification.new(request.raw_post, alipay.key, alipay.account)
          notification.data.each do |item|
            order = shop.orders.find_by_trade_no(item.trade_no)
            if order and transaction = order.transactions.pending_refund.where(batch_no: notification.batch_no).first
              transaction.status = (item.result.downcase == 'success') ? 'success' : 'failure'
              transaction.save
            end
          end
        end
        render text: 'success'
      end

    end

  end
end

app/controllers/api/v1/orders_controller.rb
# encoding: utf-8
module Api::V1
  class OrdersController < AppController
    doorkeeper_for :index, :show, scopes: [:read_orders, :write_orders], unless: lambda { @api_client }
    FIELDS = [:financial_status, :fulfillment_status]

    def index
      conditions = {}
      FIELDS.each do |field|
        conditions[field] = params[field] unless params[field].blank?
      end
      @orders = shop.orders.where(conditions).page(page).per(per_page)
    end

    def show
      @order = shop.orders.find(params[:id])
    end

  end
end

app/helpers/admin/orders_helper.rb
#encoding: utf-8
module Admin::OrdersHelper

  #查询条件链接需要存储上一次的查询条件
  def order_search_path(current_search)
    search_path(:orders_path, current_search)
  end

  def orders_menu_label
    size = orders_size
    size > 0 ? "订单 (#{size})" : "订单"
  end

  def orders_size
    shop.orders.metasearch(status_eq: :open, financial_status_ne: :abandoned).size
  end

end

app/helpers/shop/order_helper.rb
module Shop::OrderHelper
  def checkout_url(cart = nil)
    if cart
      "/carts/#{cart.token}"
    else
      session['customer_return_to'] || params['checkout_url'] # 1. 顾客结算时未跳转至checkout子域名，使用session；2. 否则发现cart未关联顾客时，使用checkout_url参数
    end
  end
end

app/views/admin/orders/_cancel.html.haml
=dialog '取消订单' do
  #cancel_order
    =form_for order, url: cancel_order_path(order) do |f|
      %p.st.ssb
        您应该取消此订单如果它是欺诈性的、顾客改变主意，或者没有商品了。取消订单是
        =succeed "." do
          %strong.highlight-alt 不可恢复的
      %p.st.ssb
        %label(for="reason") 原因:
        %select#reason(name="order[cancel_reason]")=options_for_select cancel_reasons.invert
      .pgroup
        %table#cancel-data.no-lines
          -if order.refundable?
            %tr
              %td(style="width: 200px")
                %input#refund(checked="checked" name="refund" type="checkbox" value="1")
                %label(for="refund") 退款
              %td#refund-instructions.note
                您将退回 #{shop.format_money_in_emails(order.total_price)} 给顾客。取消订单后请手动点击"退款"链接进行退款。
                -#
                  %input#amount(name="amount" size="7" type="text" value="#{order.total_price}")
          %tr
            %td(style="width: 200px; padding-top: 20px")
              %input#email(checked="checked" name="email" type="checkbox" value="1")
              %label(for="email") 发送Email
            %td.note(style="padding-top: 20px") 发送通知邮件给顾客.
      %input#submit.btn(name="commit" type="submit" value="取消此订单")
      或者
      %a.close-lightbox(href="#") 关闭此窗口

app/views/admin/orders/_conversation.html.haml
#conversion-info
  %h3 订单来源
  %ul.nobull
    %li.note
      入口网页:
      %a(href="/") \/
    %li.note
      引用网站:
      %a(href="")

app/views/admin/orders/_export.html.haml
#export-orders.box2.ssb.sst(style="display: none")
  %h3 导出您的订单
  %p.sb
    您的订单将导出为
    %strong .csv 文件
    (以逗号分隔).
  %a.btn(href="/admin/orders.csv?limit=50") Export currently shown orders
  %a.btn.sl(href="/admin/orders/export") Export Orders by Month or Quarter

app/views/admin/orders/_menu.html.haml
%h2#title 订单管理
-#
  #action-links
    %ul
      %li.small-icon
        %a.feed(href="/admin/feed") RSS订阅订单
      %li.csv
        %a(href="#") 导出订单
=render "shared/noscript"
=render "shared/upgrade_ie"
-#=render :export

app/views/admin/orders/show.html.haml
-address = order.shipping_address
%h2#title
  =order.title
  %span.hide==token: #{order.token}
  %span#order-date=order.created_at.to_s(:with_year)
#action-links
  %ul
    -#%li#email=link_to '联系顾客', '#', class: 'closeure-lightbox'
    %li#note=link_to '备注', '#'
    -#%li.csv=link_to '导出', '#'
    %li#print
      %a(href="#" onclick="window.print();; return false;") 打印
    -if order.closed_at
      %li#locko=link_to "重新打开此订单", open_order_path(order), method: :post
      %li.no-icon= link_to image_tag('admin/icons/trash.gif'), order_path(order), method: :delete, data: { confirm: '您确定要删除?' }
    -elsif !order.cancelled?
      %li#lock=link_to "关闭此订单", close_order_path(order), method: :post
      -unless order.financial_status == 'abandoned'
        %li#cancel-order=link_to "取消此订单", '#'
=render "shared/noscript"
=render "shared/upgrade_ie"
-if order.closed_at or order.cancelled_at
  .sst.pgroup.c.warn
    %p
      %strong
        -if order.closed_at
          ==此订单已于#{order.closed_at.to_s(:full)}关闭.
        -else
          ==此订单已于#{order.cancelled_at.to_s(:full)}取消.
#previous
  .tools.hide
    =link_to previous_order_path(order), class: :message do
      %em 上一订单
      %br
      %span.key 按'j'键
    %br
    .bg
#next
  .tools.hide
    =link_to next_order_path(order), class: :message do
      %em 下一订单
      %br
      %span.key 按'k'键
    %br
    .bg
.col-4
  #customer-box.box2(style="margin:20px 0 0 0; padding:10px; width:240px;")
    %table#customer-summary(cellpadding="0" cellspacing="0")
      %tr.first
        %td.attribute=link_to image_tag('admin/icons/customer.gif', id: :gravatar), customer_path(customer)
        %td.value
          %h3=link_to customer.name, customer_path(customer)
          %p(style="line-height:18px;")
            %a(href="mailto:#{customer.email}")=customer.email
            -if address
              %br
              =address.phone
      %tr
        %td.attribute 营销
        %td.value.image
          %span.o-authorized==#{customer.accepts_marketing ? "" : "不愿意"}接收营销邮件
  #ship-addr.customer-col
    .tools.hide
      .map-link
        %a(href="#" onclick="window.open('http://maps.google.com/maps?q=china,+shenzhen,+518057,+China','popup','directories=no,location=no,resizable=yes,scrollbars=yes'); return false;") 显示地图
    %h3 收货人地址
    #shipping-address.vcard
      %address.adr
        %span
          -if address
            =address.full_info
            =raw clippy(address.full_info)
          -else
            此商品不需要收货地址
      %a.email.hide(href="mailto:mahb45@gmail.com")
  #other-orders-box.customer-col.hide
    %h3(title="显示此顾客其他待处理的订单，方便一起发货") 此顾客其他订单
    #other-orders
.col-8.last
  -#=render :payment_credit
  .box2.sst(style="padding-top: 0")
    -if order.financial_status == 'abandoned'
      %h3 此订单已经被放弃
      %p.note.sb 放弃订单表示顾客选择商品后，没有完成购买操作
      %p.note
        如果您联系了顾客，并且知道对方需要继续完成购买操作，您可以将
        = succeed "." do
          %a(href="https://checkout.shopqi.com/orders/#{shop.id}/#{order.token}/pay") 此链接地址
        发送给顾客
    -else
      #order-status.order-action-line.separator.clearfix
      #order-fulfillment.order-action-line
        #unshipped-goods.fr.r
        .sb.shipping-method
          %h3 配送方式
          %p=address ? order.shipping_rate : '不需要配送'
      %form#batch_fulfillment_form(action="#" onsubmit="return false")
        #mark-shipped.hide
          .sb.order-action-line
            %h3 发货
            %p 选择您已经发货的商品
          %table.data(cellpadding="0" cellspacing="0")
          #manual_shipping_options.sb.sst.fulfillment_service_shipping_options.group(style="margin: 20px 0")
            #manual_tracking_number_container
              %h4
                快递单号
                %span.hint 可以稍后加入
              %p
                %input#manual_tracking_number.tracking-number(name="shipping_options[manual][tracking_number]" type="text" value="#{latest_tracking_number}")
                %span#manual_tracking_company_area.hide
                  通过
                  %select#manual_tracking_company(disabled="disabled" name="shipping_options[manual][tracking_company]")
                    =options_for_select tracking_companies, latest_tracking_company
          .btns(style="background: none")
            .sb
              %input#notify_customer(checked="checked" name="notify_customer" type="checkbox" value="true")
              %label.note(for="notify_customer") 发送邮件通知顾客
            %div
              %input#fulfill-items.btn(name="commit" type="submit" value="发货")
              或者
              %a.cancel(href="#") 取消
  #order-note.message.pgroup.hide
    %h3 订单备注
    #note-body
  #note-form.message.group.hide
    %form.edit_order(action="#" onsubmit='return false')
      %p.sb
        %strong 输入您的备注:
      %textarea#order_note(cols="40" name="order[note]" rows="10")
      %p.hint
      %p.actions-close
        %input.btn(name="commit" type="submit" value="保存备注")
        或者
        %a.cancel(href="#") 取消
  #order
    %table.data(cellspacing="0")
      %thead
        %tr
          %th(style="width: 16px; padding: 0 3px") &nbsp;
          %th.left 商品
          %th 价格
          %th(style="text-align:center") 数量
          %th.total-col 金额
      %tbody#line-items
      %tbody#discount
      %tbody#price-summary
  #order-history
    %h3 订单历史
    %table#order-history-table(cellspacing="0")

%script(id="other-orders-item" type="text/x-handlebars-template")
  %p
    %a(href="/admin/orders/{{id}}") {{name}}
    {{{created_at}}}
%script(id="order-status-item" type="text/x-handlebars-template")
  .fr.r
    {{#if payed}}
    {{#if refunded}}
    %h3 已退款
    {{else}}
    %h3 已支付
    %p 您已经收到此订单的款项
    -if @refund_apply_url
      %p.warn
        订单已取消，请点击
        %a(href="#{@refund_apply_url}" title="请使用 IE 浏览器，支付宝退款数字证书只支持 IE 浏览器") 退款
        前往支付网关完成退款操作
    {{/if}}
    {{else}}
    %form#transaction_new.transaction_new(action="#" onsubmit="return false")
      %input#transaction_kind(name="transaction[kind]" type="hidden" value="capture")
      %input.btn(name="commit" type="submit" value="已收到款项")
    %p.instruction.r 您还未收到此订单的款项
    %p.note
      如果您联系了顾客，对方需要继续完成购买操作，可将
      %a(href="#{show_shop_url}/orders/#{order.token}") 此链接地址
      发送给顾客
    {{/if}}
  %h3 支付方式
  %p {{gateway}}
%script(id="order-history-table-item" type="text/x-handlebars-template")
  {{#loop}}
  %tr.log-date
    %td(colspan="2") {{{created_at}}}
  {{#each histories}}
  %tr.log
    %td.log-time(style='width:50px')
      %span {{{created_at}}}
    %td
      {{#if url}}
      %a.history-link(href="{{{url}}}") {{{body}}}
      {{else}} {{{body}}} {{/if}}
  {{/each}}
  {{/loop}}
%script(id="order-history-fulfillment-item" type="text/x-handlebars-template")=render 'admin/fulfillments/show'

%script(id="unshipped-goods-item" type="text/x-handlebars-template")
  {{#if fulfilled}}
  %h3 完成发货
  %p.instruction 此订单的所有商品已经发货
  {{else}}
  %input.btn(type="button" value="发货")
  %p.instruction
    您需要准备
    %strong {{{unshipped_line_items.length}}} 款商品
  {{/if}}
%script(id="edit-fulfillment-item" type="text/x-handlebars-template")
  %td(style="width: 24px; vertical-align:middle")
    {{#if fulfilled}}
    =image_tag 'admin/icons/shipping.gif'
    {{else}}
    %input.fulfill(id="line-item-{{{id}}}" checked="checked" name="shipped[]" style="margin:0 0 2px 1px" type="checkbox" value="{{{id}}}")
    {{/if}}
  %td.c
    %strong(style="font-size: 14px") {{{quantity}}}
    x
  %td
    %strong
      %label(for="line-item-{{{id}}}")
        {{#if product_deleted}}
        {{title}}}
        {{else}}
        %a.product-link(href="/admin/products/{{{product_id}}}" title="前往商品页面") {{{title}}}
        {{/if}}
    \- {{{variant_title}}}
    %br
    {{#if fulfilled}}
    %span(class="note") 已于{{{date fulfillment_created_at}}}发货
    {{/if}}
  %td
    %label(for="line-item-{{{id}}}")
      %span.note(style="font-weight:normal") {{{sku}}}
%script(id="line-items-item" type="text/x-handlebars-template")
  %td(style="vertical-align:middle")
  %td(style="max-width:320px")
    %strong
      %label(for="line-item-{{{id}}}")
        {{#if product_deleted}}
        {{title}}}
        {{else}}
        %a.product-link(href="/admin/products/{{{product_id}}}" title="前往商品页面") {{{title}}}
        {{/if}}
    \- {{{variant_title}}}
    %br
    {{#if fulfilled}}
    %span(class="note") 已于{{{date fulfillment_created_at}}}发货
    {{/if}}
  %td.line-price {{{price}}}
  %td.line-qty.c {{{quantity}}}
  %td.total-col {{{total_price}}}
%script(id="discount-item" type="text/x-handlebars-template")
  %tr
    %td
    %td.discount-line(colspan="3")
      %strong 优惠码
      \- {{{code}}}
    %td.total-col -{{{amount}}}
%script(id="price-summary-item" type="text/x-handlebars-template")
  %tr#sep.summary
    %td.r(colspan="4") 小计:
    %td.r.subtotal.total-col {{{subtotal_price}}}
  %tr.summary
    %td.r(colspan="4") 配送费用 (快递):
    %td.r.primary.total-col {{{ shipping_rate_price }}}
  %tr#total.summary
    %td.totalnum.r(colspan="4") 总金额:
    %td.r.totalnum.total-col {{{total_price}}}
%script#cancel-order-item(type="text/x-handlebars-template")=render 'cancel'

:javascript
  App.init = function(){
    new App.Controllers.Orders.Show();
    Backbone.history.start();
  }

  App.order = new App.Models.Order(#{order_json});
  new App.Views.Order.Show.Show({model: App.order});